AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Stack 1

Resources:
  LambdaFunction1:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: lambda.handler
      Runtime: dotnetcore3.1
      CodeUri: .
      Description: ASP.NET Core Lambda function that is integrated with an API Gateway
      MemorySize: 256
      Timeout: 30
      Role: null
      Policies: AWSLambdaFullAccess
      Events:
        RootResource:
          Type: Api 
          Properties:
            Path: /lambda-stack1
            Method: any
            RestApiId: 
              Ref: MyApiGateway

Outputs:
  LambdaFunction1:
    Description: "Lambda Function ARN"
    Value: !GetAtt LambdaFunction1.Arn
  LambdaFunction1IamRole:
    Description: "Implicit IAM Role created for Lambda function"
    Value: !GetAtt LambdaFunction1Role.Arn