AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Stack 1

Resources:
  LambdaFunction1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_stack1/aspnet_app::lambda_stack1.aspnet_app.LambdaEntryPoint::FunctionHandlerAsync
      Runtime: dotnetcore3.1
      CodeUri: ./aspnet_app/
      MemorySize: 256
      Timeout: 30
      Role: arn:aws:iam::123456789012:role/lambda-role
      Events:
        RootResource:
          Type: Api
          Properties:
            Path: /lambda_stack1
            Method: ANY
            RestApiId: 
              Ref: BaseApiGateway
      Environment:
        Variables:
          ASPNETCORE_ENVIRONMENT: Development
          DynamoDBTable: 
            Ref: BaseDynamoDBTable

Outputs:
  LambdaFunction1:
    Description: Lambda function info
    Value: 
      Ref: LambdaFunction1
  LambdaFunction1Arn:
    Description: Lambda function ARN
    Value: 
      Fn::GetAtt: 
        - LambdaFunction1
        - Arn
  LambdaFunction1ApiGatewayInvokeURL:
    Description: URL for Application Load Balancer
    Value: 
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/lambda_stack1/