AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for creating base stack with API Gateway and DynamoDB Table

Resources:
  MyApiGateway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: 'MyApiGateway'
      Description: 'API Gateway for the application'

  MyDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'MyDynamoDBTable'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'

Outputs:
  ApiGatewayId:
    Description: 'API Gateway ID'
    Value: !Ref MyApiGateway
  DynamoDBTable:
    Description: 'DynamoDB Table Name'
    Value: !Ref MyDynamoDBTable