AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.

Resources:
  MyApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        info:
          title:
            Ref: AWS::StackName
        paths: {}

  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MyDynamoDBTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  ApiGatewayRestApiId:
    Description: The ID of the API Gateway REST API
    Value: !Ref MyApiGateway
  ApiGatewayRestApiRootResourceId:
    Description: The ID of the API Gateway REST API root resource
    Value: !GetAtt MyApiGateway.RootResourceId
  DynamoDBTable:
    Description: The name of the DynamoDB table
    Value: !Ref MyDynamoDBTable